language: python

python:
  - 2.7

install:
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q lxml==3.6.4
  - pip install -q mock
  - pip install -q suds
  - pip install .

before_script: cd tests

script: make coverage

after_script: coveralls --rc=coveragerc
